- hosts: localhost
  pre_tasks:
  - name: Update apt
    become: true
    apt:  
      force_apt_get: true
      update_cache: true
      state: present
    tags:
    - install
    - core
  tasks:  
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
