- name: Installing stow
  apt: name=stow
  become: true
  tags: 
    - dotfiles
    - zsh

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/rwalter215/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: 
    - dotfiles
    - zsh